### ISSUE TITLE
Content is not loaded on post.

### ISSUE THREAD

**Issue by gauravt** [royboy789/angularjs-for-wordpress#4]
After publishing post with angular enabled, its not showing the post.

![screenshot from 2015-03-23 18 31 42](https://cloud.githubusercontent.com/assets/1091887/6780402/e14b1f1c-d18a-11e4-99b4-19e313df69bc.png)

**Comment by 8bitsquid** [comment]
I just ran into the same issue. I installed through WP,but apparently the Github repo is different. From the looks of it, if you download from github and re-install it should work.

If you installed through WP and just want to edit the current files, taking these steps should work:

In `angularjs-for-wp/includes/contentFilter.php` remove this (I think on line 6):
```php
// $content gets wrapped with ng-app, but you'll notice a few lines down it gets overwritten.
$content = '<div ng-app="wpAngularPlugin">'.$content.'</div>';
```

In `angularjs-for-wp/js/angular-app.js` add this line at the top:
```javascript
jQuery('html').attr('ng-app', 'wpAngularPlugin');
```

**Comment by royboy789** [comment]
sorry haven't updated the repo.. yes the problem with that approach is that any other apps that want to run within your site can't since sub-apps are not able to run.

**Comment by royboy789** [comment]
@gauravt - is this when you use the checkbox to load the page with Angular or using the shortcode?

**Comment by royboy789** [comment]
This should be fixed now..
