### ISSUE TITLE
ng-bind-html stripping id attributes

### ISSUE THREAD

**Issue by DaveLindberg** [royboy789/angularjs-for-wordpress#6]
HTML:  `<div ng-bind-html="post.content | unsafe"></div>`
Template: single-detail.html
Wordpress content: `...<div class="well 8em" id="brands">...`
Renders as: `...<div class="well 8em">...`

See the results at http://dev.davelindberg.com. 

Looks similar to <a href="https://github.com/fraywing/textAngular/issues/355">ID attribute from link gets filtered out</a>?

**Comment by royboy789** [comment]
hmm I will look at this.. stay tuned..

**Comment by royboy789** [comment]
pushed to WP repo - v 1.2.2
