### ISSUE TITLE
JSON REST API must be installed

### ISSUE THREAD

**Issue by Maaark** [royboy789/angularjs-for-wordpress#7]
After installing the plugin it keeps saying: JSON REST API must be installed and activated for the AngularJS for WP plugin to work properly - Install Plugin, even when I've installed this plugin.

**Comment by royboy789** [comment]
yes, i updated the notice to be compliant with v2 of the API, but the same condition fails with any version prior.

**Comment by royboy789** [comment]
Fixed in commit, moving forwards API v2 a77770c9270fd03e354585d681d5bf983b8fd4a4
